### ISSUE TITLE
多聚焦

### ISSUE THREAD

**Issue by xiaokedouaa** [ytZhang99/U2Fusion-pytorch#5]
我想问一下为什么test进行图像融合时，图像交叉融合，不是按照lable来进行融合

**Comment by ytZhang99** [comment]
不好意思没太看明白您的意思是什么，可以说得详细一点吗

**Comment by xiaokedouaa** [comment]
是我的图像标签错了，我想问一下，你有将denset模型变为其他的模型来进行训练吗

**Comment by ytZhang99** [comment]
没有，因为就目前来说U2fusion的融合效果已经比不上很多算法了，你也可以将DenseNet模型替换为ResNet、Transformer等主干网络结构来尝试一下

**Comment by xiaokedouaa** [comment]
好的，那个特征提取模块也可以换为其他的网络？？
